### ISSUE TITLE
Add functionnal tests to JShellAPI ?

### ISSUE THREAD

**Issue by Alathreon** [Together-Java/JShellPlaygroundBackend#30]
While  the wrapper is tested, the REST API isn't, which can cause some problems, because of the sheer number of moving pieces.
So adding tests that verify that the REST API works would be very useful.
Only problem, the REST API needs docker.

**Comment by firasrg** [comment]
Hello folks! This is a recap about the work in my PR #50, it was a long journey 😄 ! While it has not been merged yet, I believe it is currently ready as all reviews have been resolved now. 

**Acknowledgment** : I’d like to thank @Alathreon and @surajkumar who provided me with good hints before I start. Also for their trust and assistance during development and PR review process.

### Work Done

1. **Test Dependencies & [Gradle ](https://gradle.org/)Setup** : Verified necessary test dependencies within the [**build.gradle** file](https://docs.gradle.org/current/userguide/build_file_basics.html) of [JShellAPI subproject](https://github.com/Together-Java/JShellPlaygroundBackend/blob/develop/JShellAPI/build.gradle).

2. **Gradle Test Setup** : I created 2 new [Gradle tasks ](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html) under a new group named as "Docker" : 
```groovy
test {
    dependsOn taskBuildDockerImage
    finalizedBy taskRemoveDockerImage
}
```
👉 Currently, these tasks were integrated only for testing.

NOTE: _Some Gradle knowledge was required here. Contributors unfamiliar with Gradle should consult Gradle's documentation before proceeding._

3. **Test Class Setup** : I initially thought using [@SpringBootTest](https://docs.spring.io/spring-boot/api/java/org/springframework/boot/test/context/SpringBootTest.html) alone was sufficient. However, I found it necessary to add [@ContextConfiguration](https://docs.spring.io/spring-framework/reference/testing/annotations/integration-spring/annotation-contextconfiguration.html) for proper context initialization.

```java
@ContextConfiguration(classes = Main.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class JShellApiTests {
   // class body
}
```
4. **Test Method Design** : I used the a combination of [@Test](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Test.html) annotation with [@DisplayName](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/DisplayName.html) to provide a clear description about the test.

```java
@Test
@DisplayName("More concise and explicit description about the test")
public void myTest() { }
```
5. **Dependency Conflict**: upon launching the test, I encountered a conflict with the [logback-classic](https://mvnrepository.com/artifact/ch.qos.logback/logback-classic) dependency. After a quick search [on **StackOverflow**](https://stackoverflow.com/questions/30792268/loggerfactory-is-not-a-logback-loggercontext-but-logback-is-on-the-classpath), I resolved this by excluding it from the test dependencies in build.gradle:

```groovy
testImplementation('org.springframework.boot:spring-boot-starter-test') {
  exclude group: 'ch.qos.logback', module: 'logback-classic'
}
```

6. **Testing Process** : I wrote the test logic using the [WebTestClient API](https://docs.spring.io/spring-framework/reference/testing/webtestclient.html) from [Spring WebFlux](https://docs.spring.io/spring-framework/reference/web/webflux.html), which proved simpler than [MockMvc](https://docs.spring.io/spring-framework/reference/testing/spring-mvc-test-framework.html).

```java
this.webTestClient.mutate()
            .responseTimeout(Duration.ofSeconds(appConfig.evalTimeoutSeconds()))
            .build()
            .post()
            .uri(endpoint)
            .bodyValue(codeInput)
            .exchange()
            .expectStatus()
            .isOk()
            .expectBody(JShellResult.class)
            .value((JShellResult evalResult) -> assertThat(evalResult).isNotNull())
            .returnResult()
            .getResponseBody();
```
7. **Evaluating Multiple Requests in 1 Test** : After the initial PR, @Alathreon suggested performing **at least 2** evaluations to ensure test robustness. I implemented this, simulating 2 API calls with the same session, reusing variables across calls. This approach ensures that the functionality works consistently across requests.

8. **Cleanup** : Some final cleanup and optimization of the changed classes, ensuring everything is neat and functional.

Thanks for reading and see you in the next integration test !
